---
# Global variables for this TTN organization

# Conduits do not have sudo and su dows not work with Ansible
ansible_user: root

# User to log in and poke around on a Conduit
ttn_user: wework

# Tunnel to SSH server
ssh_tunnel_remote_user: wework
ssh_tunnel_remote_host: 54.174.31.221
ssh_tunnel_ssh_port: 22

# Which TTN packet forwarder to install
# 'poly' for Kersing version 2.*
# 'mp' for Kersing version 3.*
forwarder_variant: mp
forwarder_version: 3.0.0-r14

# Pick a value from /usr/share/zoneinfo/REGION/ZONE, i.e. US/Eastern
timezone: "US/Eastern"

# Pick the correct region:
# AS1	AS_920_923	Asia 1
# AS2	AS_923_925	Asia 2
# AU	AU_915_928	Australia
# EU	EU_863_870	Europe
# KR	KR_920_923	Korea
# IN	IN_865_867	India
# US	US_902_928	US
region: US

# Pick a router ( switch-router ttn-router-asia-se ttn-router-brazil ttn-router-eu ttn-router-us-west )
router: ttn-router-us-west

# Whom to contact about issues with this gateway
contact_email: ajackson@wework.com

# Collaborators
gateway_collaborators:
  - { username: jkachmar }
  - { username: Tombar }

# Pick servers appropriate for the installed region
ntp_servers:
  - 0.north-america.pool.ntp.org
  - 1.north-america.pool.ntp.org
  - 2.north-america.pool.ntp.org

ssh_tunnel_keepalive_base_port: 1000
ssh_tunnel_gateway_user_on_jumphost: wework
